### ISSUE TITLE
[BUG]弹幕接收存在稳定性问题

### ISSUE THREAD

**Issue by planktonzp** [OctavianLee/Barrage#12]
大概8分钟会崩溃一次，如果有时间的话请调试

**Comment by OctavianLee** [comment]
okay

**Comment by OctavianLee** [comment]
@ruizhipeng 想问一下你的环境命令行的存储大小是多少，因为终端超过量之后会崩溃，通常设大一点会好一点。

**Comment by planktonzp** [comment]
如果是问回滚量的话我设置的1000行，如果是指缓存的话，我也不太清楚。。。不过我想如果添加一个将超出内容转存至本地日志或清除的选项会不会好一点？

**Comment by OctavianLee** [comment]
问题不是在这里，而是命令行输出有限制，存到本地也会如此，这就是命令行终端本身的设计。

**Comment by planktonzp** [comment]
发现一个用node.js写的 终端弹幕机  https://coding.net/u/payne/p/bili-comment/git  你看一下是否有可用的地方

**Comment by OctavianLee** [comment]
粗略看了一下，这个已经好久没更新的，现在b站获取内容都改了，因此参考性不强，不过能看一下他如何设计结构的。

**Comment by planktonzp** [comment]
以及他这个好像可以输出弹幕到日志，可以作为后续插件的参考，看了下他的配置文件，获取基本的弹幕和在线人数貌似还能用

**Comment by planktonzp** [comment]
壮士快来更新源码 2333

**Comment by OctavianLee** [comment]
稍等 最近事务过多，每天休息时间已经不足7个小时

**Comment by OctavianLee** [comment]
@ruizhipeng 已经好了

**Comment by planktonzp** [comment]
好的 感谢
