### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by JO-WTF** [OctavianLee/Barrage#14]
在登录的时候请求失败。

提示requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by JO-WTF** [comment]
试验了一下，发现用cookie登录是最简单的方法。

http://jo.wtf/利用cookie登录bilibili发送弹幕/

**Comment by superfashi** [comment]
cookie固然可以，但是对于用户太过麻烦。
失效是因为b站前几个月改了url，接口还是没问题的。

**Comment by JO-WTF** [comment]
我看到了，account改成了passport。我觉得其实cookie对于普通用户是更方便的，毕竟省略了登录环节（当然需要写代码自动去读取Cookie）。

各有各的好处吧，比如我如果想开个小号发弹幕，当然还是登录比较合适。
